# Generated by Django 4.1.1 on 2022-09-26 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuboid',
            name='creation_date',
            field=models.DateField(default=datetime.date(2022, 9, 26)),
        ),
    ]
