# Generated by Django 4.1.1 on 2022-09-24 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuboid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('breath', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created_by', models.CharField(max_length=25)),
                ('last_updated', models.CharField(max_length=25)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuboids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
